src/GeneratorOfReports/Models/Report.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorOfReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.AuthorizationReports = new HashSet<AuthorizationReport>();
            this.ReportQueries = new HashSet<ReportQuery>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
        public bool Valid { get; set; }
        public Nullable<System.DateTime> TimeCreate { get; set; }
        public int UserCreateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorizationReport> AuthorizationReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportQuery> ReportQueries { get; set; }
    }
}

src/GeneratorOfReports/ViewModels/ReportViewModels/ReportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GeneratorOfReports.ViewModels
{
    public class ReportViewModel
    {
        public int? ID { get; set; }

        [Display(Name = "Global_Name", ResourceType = typeof(Resources.Translation))]
        [Required(ErrorMessageResourceType = typeof(Resources.Translation), ErrorMessageResourceName = "Report_Name_ErrorMessage_Required", AllowEmptyStrings = false)]
        [MaxLength(int.MaxValue, ErrorMessageResourceType = typeof(Resources.Translation), ErrorMessageResourceName = "Global_ErrorMessage_ExceededMax")]
        public string Name { get; set; }

        [Display(Name = "Global_Description", ResourceType = typeof(Resources.Translation))]
        [MaxLength(int.MaxValue, ErrorMessageResourceType = typeof(Resources.Translation), ErrorMessageResourceName = "Global_ErrorMessage_ExceededMax")]
        public string Description { get; set; }

        [Display(Name = "Global_Valid", ResourceType = typeof(Resources.Translation))]
        public bool Valid { get; set; }
        public string ValidWord { get; set; }

        [Display(Name = "Report_Order", ResourceType = typeof(Resources.Translation))]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources.Translation), ErrorMessageResourceName = "Report_Order_ErrorMessage_Positive")]
        public int Order { get; set; }
        public int Maximum { get; set; }

        [Display(Name = "Global_TimeCreate", ResourceType = typeof(Resources.Translation))]
        public string TimeCreate { get; set; }
    }
}

src/GeneratorOfReports/Controllers/ReportController.cs
using GeneratorOfReports.Authentication;
using GeneratorOfReports.Models;
using GeneratorOfReports.Services;
using GeneratorOfReports.Utilities;
using GeneratorOfReports.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GeneratorOfReports.ReportGenerator;
using GeneratorOfReports.Resources;
using GeneratorOfReports.ReportGenerator.POCO;
using GeneratorOfReports.ParameterManagement;

namespace GeneratorOfReports.Controllers
{
    [Authorize(Roles = RolesConstants.REPORT_ADMIN)]
    public class ReportController : BaseController
    {
        #region Properties

        private readonly ReportService _reportService;
        private readonly QueryService _queryService;
        private readonly ParameterService _parameterService;
        private readonly AuthorizationService _authorizationService;
        private readonly LocalityService _localityService;

        #endregion

        #region Constructor

        public ReportController()
        {
            _reportService = new ReportService(UnitOfWork);
            _queryService = new QueryService(UnitOfWork);
            _parameterService = new ParameterService(UnitOfWork);
            _localityService = new LocalityService(UnitOfWork);
            _authorizationService = new AuthorizationService(UnitOfWork);
        }

        #endregion

        #region Overview

        public ActionResult Overview() => View();

        #endregion

        #region Details

        [HttpPost]
        public ActionResult LoadReport(int ID, string partialName)
            => PartialView(partialName, CreateDetailsViewModel(ID));

        [NonAction]
        private ReportDetailsViewModel CreateDetailsViewModel(int ID)
        {
            Report report = _reportService.Get(ID);
            int localityID = (User as Principal).CurrentLocalityID;
            bool canEdit = _reportService.CanEdit(report, localityID);

            return new ReportDetailsViewModel
            {
                Report = _reportService.CreateReportViewModel(report),
                CanEdit = canEdit,
                Queries = report.ReportQueries.Select(x =>
                {
                    var q = _queryService.CreateQueryViewModel(x.Query);
                    q.Count = x.Count;
                    return q;
                }),
                Authorization = canEdit ? report.AuthorizationReports.Select(x => _authorizationService.CreateAuthorization(x.Authorization, x.Locality.Name)) : null
            };
        }

        #endregion

        #region Modify 

        #region Remove

        [HttpPost]
        public ActionResult Remove(int ID)
        {
            bool removed = _reportService.Remove(ID, (User as Principal).CurrentLocalityID);
            return Json(removed, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Create 

        public ActionResult Create()
            => View(_reportService.CreateReportCreateViewModel());

        [HttpPost]
        public ActionResult Create(ReportCreateViewModel model)
        {
            if (ModelState.IsValid && CheckIsSmallerOrder(model.Report.Order, 1) &&
                _queryService.ValidCreateQueries(model.Queries))
            {
                var user = (User as Principal);
                var authorizations = _authorizationService.CreateAuthorizationReports(model.Authorization, user.CurrentLocalityID);
                _reportService.AddReport(model, authorizations, user.ID);
                NotificationUtility.Add(new Notification("success", Translation.Report_Create, Translation.Report_Create_SuccessMessage));
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Edit

        [HttpPost]
        public ActionResult Edit(ReportCreateViewModel model)
        {
            if (ModelState.IsValid && CheckIsSmallerOrder(model.Report.Order, 0) &&
                _queryService.ValidCreateQueries(model.Queries))
            {
                var authorizations = _authorizationService.CreateAuthorizationReports(model.Authorization, (User as Principal).CurrentLocalityID);
                _reportService.Update(model, authorizations);
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Basics Settings

        [HttpPost]
        public ActionResult CheckBasicsSettingsForm(ReportViewModel model)
        {
            if (ModelState.IsValid && CheckIsSmallerOrder(model.Order, 1))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            FetchErrors();
            return PartialView("Forms/_ReportBasicsSettingsForm", model);
        }

        #endregion

        #endregion

        #region Generate

        public ActionResult Generate(int? modelID)
        {
            if (modelID == null)
            {
                return View(new GenerateReportViewModel { Message = Translation.Report_Generate_Error_SelectReport });
            }

            int ID = (int)modelID;
            GenerateReportViewModel model;
            if (!_reportService.IsVisible(ID, (User as Principal).CurrentLocalityID))
            {
                model = new GenerateReportViewModel { Message = Translation.Report_Generate_Error_SelectReport };
            }
            else if (!_reportService.CanGenerate(ID))
            {
                model = new GenerateReportViewModel { Message = Translation.Report_Generate_Error_Valid };
            }
            else
            {
                model = CreateGenerateReportViewModel(ID);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Generate(GenerateReportViewModel model)
        {
            if (model != null && model.Report != null &&
                model.Settings != null && ValidQueries(model.Queries))
            {
                GeneratedReport queries = CreateGeneratedReport(model);
                Session["Download_Data"] = Generator.Generate(queries);
                Session["Download_Name"] = model.Report.Name + "." + model.Settings.Format;
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            return Json(false, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Download()
        {
            string name = Session["Download_Name"] as string;
            byte[] data = Session["Download_Data"] as byte[];
            return File(data, "application/octet-stream", name);
        }

        [ChildActionOnly]
        public ActionResult GenerateParameterTypeForm(ParameterViewModel parameter)
        {
            ParameterType t = ParameterTypes.GetValue(parameter.Keyword).Type;
            return PartialView(t.PartialName, t.GetViewModel(parameter.ModelJson, parameter.DefaultValueModel));
        }

        #region Formattors

        [NonAction]
        private GeneratedReport CreateGeneratedReport(GenerateReportViewModel model)
            => new GeneratedReport
            {
                Name = model.Report.Name,
                Description = model.Report.Description,
                UserCreated = (User as Principal).FirstName + " " + (User as Principal).LastName,
                Settings = model.Settings,
                Queries = _queryService.CreateGeneratedQuery(model.Queries)
            };

        [NonAction]
        private GenerateReportViewModel CreateGenerateReportViewModel(int ID)
        {
            Report report = _reportService.Get(ID);
            return new GenerateReportViewModel
            {
                Settings = new Settings { },
                FormatSelectList = FormattingUtility.GetEnumSelectList<Format>(),
                Report = _reportService.CreateReportViewModel(report),
                Queries = _queryService.CreateReportQueryViewModel(report.ReportQueries)
            };
        }

        #endregion

        #region Validators

        [HttpPost]
        public ActionResult ValidateQueryParameter(ParameterViewModel model)
        {
            if (ModelState.IsValid)
            {
                (bool valid, string message) = _parameterService.ValidParametr(model);

                if (valid)
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    ModelState.AddModelError("Value", message);
                }
            }

            return PartialView("Forms/_QueryParameterForm", model);
        }

        [NonAction]
        private bool ValidQueries(IEnumerable<ReportQueryViewModel> queries)
         => queries != null &&
            queries.Any() &&
            queries.ToList().TrueForAll(x => _parameterService.ValidParameters(x.Parameters));

        #endregion

        #endregion

        #region Searching 

        [ChildActionOnly]
        public ActionResult GenerateSearchForm()
        {
            ReportSearchViewModel model = new ReportSearchViewModel
            {
                ValidSelectList = FormattingUtility.GetBooleanSelectList()
            };
            return PartialView("Forms/_ReportSearchForm", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult LoadReportsTableData()
        {
            var draw = Request.Form.GetValues("draw")?.FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 10;
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();

src/GeneratorOfReports/Views/Report/Create.cshtml
@model GeneratorOfReports.ViewModels.ReportCreateViewModel
@{ ViewBag.Title = GeneratorOfReports.Resources.Translation.Report_Create; }

<!-- BEGIN CREATE REPORT -->
<section class="container-white">
    <div class="container">
        <div class="row col-12">
            <h2>@GeneratorOfReports.Resources.Translation.Report_Create</h2>
        </div>
        <!-- BEGIN BASICS SETTINGS -->
        <section class="col-12 border-top">
            <h3>@GeneratorOfReports.Resources.Translation.Global_BasicsSettings</h3>
            @{Html.RenderPartial("Forms/_ReportBasicsSettingsForm", Model.Report);}
        </section>
        <!-- END BASICS SETTINGS -->
        <!-- BEGIN SELECT QUERIES SECTION -->
        <section class="border-top">
            <h3>
                @GeneratorOfReports.Resources.Translation.Query_Select_Queries
            </h3>
            @{ Html.RenderAction("GenerateSelectQueriesTable", "Report"); }
            <fieldset>
                @Html.ValidationMessage("", new { @id = "queriesValidationMessage" })
            </fieldset>
        </section>
        <!-- END SELECT QUERIES SECTION -->
        <!-- BEGIN AUTHORIZATION -->
        <section class="border-top">
            <div class="row">
                <h3>
                    @GeneratorOfReports.Resources.Translation.Global_Authorization
                </h3>
                <!-- BEGIN TOOLTIP -->
                <div class="tooltip">
                    <span class="fa fa-question-circle"></span>
                    <span class="tooltiptext">@GeneratorOfReports.Resources.Translation.Authorization_Tooltip</span>
                </div>
                <!-- END TOOLTIP -->
            </div>
            @Html.Partial("Tables/_AuthorizationTable")
        </section>
        <!-- END AUTHORIZATION -->
        <!-- BEGIN BUTTONS -->
        <div class="row border-top">
            <div class="items-right">
                <!-- CREATE BUTTON -->
                <button id="createReportButton" class="btn btn-orange-sm">
                    @GeneratorOfReports.Resources.Translation.Report_Create
                    <span class="fa fa-check"></span>
                </button>
            </div>
        </div>
        <!-- END BUTTONS -->
    </div>
</section>
<!-- END CREATE REPORT -->

@{Html.RenderPartial("Modals/_ConfirmationModal","");}

@section scripts {
    @GeneratorOfReports.Utilities.LocalizationUtility.LocalizeBundle("~/bundles/translated/report/modify")
    @GeneratorOfReports.Utilities.LocalizationUtility.LocalizeBundle("~/bundles/translated/report/selectQueries")
    @Scripts.Render("~/Scripts/Custom/authorization.js")
}

src/GeneratorOfReports/Views/Report/Generate.cshtml
@model GeneratorOfReports.ViewModels.GenerateReportViewModel
@{ ViewBag.Title = GeneratorOfReports.Resources.Translation.Report_Generate; }

<!-- BEGIN GENERATE REPORT -->
<section class="container-white">
    <div class="container">
        <!-- BEGIN ROW -->
        <div class="row">
            <!-- BACK (OVERVIEW) REPORT BUTTON -->
            <a href="/Report/Overview" class="btn btn-white-sm">
                <span class="fa fa-arrow-left"></span>
                @GeneratorOfReports.Resources.Translation.Global_BackToOverview
            </a>
            <!-- TITLE -->
            <div class="items-right">
                <h1>@GeneratorOfReports.Resources.Translation.Report_Generate</h1>
            </div>
        </div>
        <!-- END ROW -->
        @if (Model == null || Model.Message != null)
        {
            <div class="border-top text-center">
                @Model.Message
            </div>
        }
        else
        {
            <!-- BEGIN BASICS INFORMATION -->
            <div class="border-top">
                <form id="reportBasicsDetails" class="container-black">
                    <div class="row">
                        <h5>@GeneratorOfReports.Resources.Translation.Global_BasicsSettings</h5>
                    </div>
                    @Html.Hidden("ID", Model.Report.ID, new { @id = "reportIdentifier" + Model.Report.ID })
                    <div class="row">
                        <!-- NAME -->
                        <div class="col-3">
                            <p class="p-small">
                                @GeneratorOfReports.Resources.Translation.Global_Name
                                @Html.Hidden("Name", Model.Report.Name)
                            </p>
                            <p>
                                @Html.DisplayTextFor(model => model.Report.Name)
                            </p>
                        </div>
                        <!-- TIME CREATE -->
                        <div class="col-3">
                            <p class="p-small">
                                @GeneratorOfReports.Resources.Translation.Global_TimeCreate
                            </p>
                            <p>
                                @Html.DisplayTextFor(model => model.Report.TimeCreate)
                            </p>
                        </div>
                        <!-- DESCRIPTION -->
                        <div class="col-6">
                            <p class="p-small">
                                @GeneratorOfReports.Resources.Translation.Global_Description
                            </p>
                            <p>
                                @Html.DisplayTextFor(model => model.Report.Description)
                            </p>
                        </div>
                    </div>
                </form>
            </div>
            <!-- END BASICS INFORMATION -->
            <!-- BEGIN MULTIPLE STEPS FORM -->
            <div id="multipleStepsForm">
                <!-- BEGIN BASICS SETTINGS -->
                <section>
                    <h4>@GeneratorOfReports.Resources.Translation.Global_BasicsSettings</h4>
                    <form id="reportBasicsSettings" class="border-top">
                        <div class="row">
                            <p class="form-check">@GeneratorOfReports.Resources.Translation.Report_Format</p>
                            <fieldset class="col-4">
                                @Html.DropDownList("Format", Model.FormatSelectList)
                            </fieldset>
                        </div>
                    </form>
                </section>
                <!-- END BASICS SETTINGS -->
                <!-- BEGIN QUERIES SETTINGS -->
                <section>
                    <h4 class="hide">@GeneratorOfReports.Resources.Translation.Query_Queries</h4>
                    @if (Model.Queries != null)
                    {
                        foreach (var query in Model.Queries)
                        {
                            <div class="container container-gray querySettings">
                                <!-- BEGIN QUERY -->
                                <h4>@GeneratorOfReports.Resources.Translation.Report_Query</h4>
                                <!-- BEGIN BASICS INFORMATION -->
                                <form class="border-top">
                                    <h5>@GeneratorOfReports.Resources.Translation.Global_BasicsSettings</h5>
                                    <input name="ID" type="hidden" value="@query.Query.ID">
                                    <!-- NAME -->
                                    <div class="row">
                                        <div class="col-3 vertical-group">
                                            <p class="p-small">
                                                @GeneratorOfReports.Resources.Translation.Global_Name
                                            </p>
                                            <p>
                                                @Html.DisplayFor(Model => query.Query.Name)
                                            </p>
                                        </div>
                                        <!-- NAME -->
                                        <div class="col-2 vertical-group">
                                            <p class="p-small">
                                                @GeneratorOfReports.Resources.Translation.Global_TimeCreate
                                            </p>
                                            <p>
                                                @Html.DisplayFor(Model => query.Query.TimeCreate)
                                            </p>
                                        </div>
                                        <!-- DESCRIPTION -->
                                        <div class="col-7 vertical-group">
                                            <p class="p-small">
                                                @GeneratorOfReports.Resources.Translation.Global_Description
                                            </p>
                                            <p>
                                                @Html.DisplayFor(Model => query.Query.Description)
                                            </p>
                                        </div>
                                    </div>
                                </form>
                                <!-- END BASICS INFORMATION -->
                                <!-- BEGIN PARAMETERS -->
                                <h5 class="border-top">@GeneratorOfReports.Resources.Translation.Query_Parameters</h5>
                                <div>
                                    @if (query.Parameters.Any())
                                    {
                                        foreach (var parameter in query.Parameters)
                                        {
                                            <!-- BEGIN PARAMETER -->
                                            <div class="parameterSettings container-darkgray">
                                                @{Html.RenderPartial("Forms/_QueryParameterForm", parameter);}
                                            </div>
                                            <!-- END PARAMETER -->
                                        }
                                    }
                                    else
                                    {
                                        <p>@GeneratorOfReports.Resources.Translation.Query_Parameter_None</p>
                                    }
                                </div>
                                <!-- END PARAMETERS -->
                            </div>
                            <!-- END QUERY -->
                        }
                    }
                </section>
                <!-- END QUERIES SETTINGS -->
            </div>
            <!-- END MULTIPLE STEPS FORM -->
        }
    </div>
</section>
<!-- END GENERATE REPORT -->

@section scripts {
    @GeneratorOfReports.Utilities.LocalizationUtility.LocalizeBundle("~/bundles/translated/report/generate")
}

src/GeneratorOfReports/Views/Report/Overview.cshtml
@{ ViewBag.Title = GeneratorOfReports.Resources.Translation.Report_Overview; }

<!-- BEGIN REPORTS OVERVIEW -->
<section id="reportsOverview">
    <div class="container-white">
        <div class="container">
            <h1>@GeneratorOfReports.Resources.Translation.Report_Overview</h1>
            <div class="row border-top">
                <!-- TOGGLE FILTERS BUTTON -->
                <button class="btn btn-white-sm hideShowToggler">
                    @GeneratorOfReports.Resources.Translation.Global_Search
                    <span class="fa fa-chevron-down icon-show"></span>
                    <span class="fa fa-caret-down icon-hide hide"></span>
                </button>
                <!-- CREATE USER BUTTON -->
                <div class="items-right">
                    <a href="/Report/Create" class="btn btn-orange-sm">
                        @GeneratorOfReports.Resources.Translation.Report_Create
                        <span class="fa fa-plus"></span>
                    </a>
                </div>
            </div>
            <!-- BEGIN HIDE AND SHOW ELEMENT -->
            <div class="hideAndShowElement hide">
                @{ Html.RenderAction("GenerateSearchForm", "Report"); }
            </div>
            <!-- END HIDE AND SHOW ELEMENT -->
            <!-- BEGIN REPORTS TABLE PARTIAL -->
            <div class="border-top">
                @{Html.RenderPartial("Tables/_ReportsTable");}
            </div>
            <!-- END REPORTS TABLE PARTIAL -->
        </div>
    </div>
</section>
<!-- END REPORTS OVERVIEW -->
<!-- BEGIN REPORT MODAL -->
<div id="reportModal">
</div>
<!-- END REPORT MODAL -->
<!-- BEGIN CHANGE ORDER SECTION -->
<div id="editOrderSection">
</div>
<!-- END CHANGE ORDER SECTION -->
@{Html.RenderPartial("Modals/_ConfirmationModal");}

@section Scripts {
    @GeneratorOfReports.Utilities.LocalizationUtility.LocalizeBundle("~/bundles/translated/report/overview")
    @GeneratorOfReports.Utilities.LocalizationUtility.LocalizeBundle("~/bundles/translated/report/modify")
    @GeneratorOfReports.Utilities.LocalizationUtility.LocalizeBundle("~/bundles/translated/report/selectQueries")
    @Scripts.Render("~/Scripts/Custom/authorization.js")
    @Scripts.Render("~/Scripts/Custom/authorizationDetails.js")
}